# Generated by Django 3.0.7 on 2020-06-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('api_secret', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, default='USD', max_length=20)),
                ('side', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('price', models.FloatField()),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
    ]
